BookStoreAZ.Web/Controllers/AdminBookController.cs
using AutoMapper;
using BookStoreAZ.ActionService;
using BookStoreAZ.Business;
using BookStoreAZ.MVC.Models;
using X.PagedList;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace BookStoreAZ.MVC.Controllers
{
    public class AdminBookController : Controller
    {
        private IService Service { get; set; }

        static AdminBookController()
        {
            Mapper.CreateMap<Book, BookModel>();
            Mapper.CreateMap<BookModel, Book>();
            Mapper.CreateMap<Publisher, PublisherModel>();
            Mapper.CreateMap<PublisherModel, Publisher>();
            Mapper.CreateMap<Author, AuthorModel>();
            Mapper.CreateMap<AuthorModel, Author>();
            Mapper.CreateMap<Category, CategoryModel>();
            Mapper.CreateMap<CategoryModel, Category>();
        }

        public AdminBookController() : this(new Service())
        {
        }

        public AdminBookController(IService service)
        {
            this.Service = service;
        }

        // GET: BookManagement
        public ActionResult Index(int page = 1, string message = null)
        {
            var model = new BooksModel { Message = message };
            var pagedBooks = Service.GetBooks(page);
            var books = Mapper.Map<IEnumerable<Book>, IEnumerable<BookModel>>(pagedBooks.ToArray());
            model.Books = new StaticPagedList<BookModel>(books, pagedBooks.GetMetaData());
            return View(model);
        }

        [HttpGet]
        public ActionResult AddOrEditBook(int id = 0)
        {
            NewBookModel model = new NewBookModel();
            BookModel bookModel = new BookModel();

            var book = Service.GetBook(id);

            if (id > 0 && book != null)
            {
                bookModel = Mapper.Map<Book, BookModel>(book);
                ViewBag.Title = "Edit book";
            }
            else
            {
                bookModel.Status = true;
                ViewBag.Title = "Add Book";
            }

            var categories = Service.GetCategories();
            IEnumerable<CategoryModel> categoryModel = Mapper.Map<IEnumerable<Category>, IEnumerable<CategoryModel>>(categories);
            bookModel.Categories = categoryModel;

            var publishers = Service.GetPublishers();
            IEnumerable<PublisherModel> publisherModel = Mapper.Map<IEnumerable<Publisher>, IEnumerable<PublisherModel>>(publishers);
            bookModel.Publishers = publisherModel;

            var authors = Service.GetAuthors();
            IEnumerable<AuthorModel> authorModel = Mapper.Map<IEnumerable<Author>, IEnumerable<AuthorModel>>(authors);
            bookModel.Authors = authorModel;

            model.Book = bookModel;

            return View(model);
        }

        [HttpPost]
        public ActionResult AddOrEditBook(NewBookModel newModel)
        {
            if (ModelState.IsValid)
            {
                var book = Mapper.Map<BookModel, Book>(newModel.Book);
                string message;
                if (book.ID > 0)
                {
                    Service.UpdateBook(book);
                    message = "Book successfully updated";
                }
                else
                {
                    Service.InsertBook(book);
                    message = "Book successfully added";
                }
                return RedirectToAction("Index", new { message = message });
            }
            else
            {
                var categories = Service.GetCategories();
                IEnumerable<CategoryModel> categoryModel = Mapper.Map<IEnumerable<Category>, IEnumerable<CategoryModel>>(categories);
                newModel.Book.Categories = categoryModel;

                var publishers = Service.GetPublishers();
                IEnumerable<PublisherModel> publisherModel = Mapper.Map<IEnumerable<Publisher>, IEnumerable<PublisherModel>>(publishers);
                newModel.Book.Publishers = publisherModel;

                var authors = Service.GetAuthors();
                IEnumerable<AuthorModel> authorModel = Mapper.Map<IEnumerable<Author>, IEnumerable<AuthorModel>>(authors);
                newModel.Book.Authors = authorModel;
            }
            return View(newModel);
        }
    }
}

BookStoreAZ.Web/Views/AdminBook/Index.cshtml
@using X.PagedList.Mvc
@using X.PagedList.Mvc.Common;

@model BookStoreAZ.MVC.Models.BooksModel

@{
    ViewBag.Title = "Manage Book";
    Layout = "~/Views/Layout/_AdminLayout.cshtml";
}

<h3>Book Management</h3>


@if (@Model.Message != null)
{
    <div class="alert alert-primary col-md-6 mx-auto" role="alert">
        @Model.Message
    </div>
}

<div class="card-body">
    <div class="table-responsive">
        <table class="table table-bordered"
               width="100%"
               cellspacing="0">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th class="text-center">Image</th>
                    <th class="text-right">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right">Action</th>
                </tr>
            </thead>
            <tfoot>
                <tr>
                    <th>Name</th>
                    <th>Description</th>
                    <th class="text-center">Image</th>
                    <th class="text-right">Price</th>
                    <th class="text-center">Quantity</th>
                    <th class="text-right">Action</th>
                </tr>
            </tfoot>
            <tbody>
                @foreach (var book in Model.Books)
                {
                    <tr>
                        <td>@book.Name</td>
                        <td>@book.Description</td>
                        <td class="text-center">
                            <img src="@book.Image" width="150" />
                        </td>
                        <td class="text-right">
                            @book.Price
                        </td>
                        <td class="text-center">@book.Quantity</td>
                        <td class="text-right">
                            <a class="btn btn-primary" href="~/Admin/ManageBook/@book.ID">
                                <i class="fas fa-edit"></i>
                                Edit
                            </a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    <div class="row align-items-center">
        <div class="col-md-6">
            Page @(Model.Books.PageCount < Model.Books.PageNumber ? 0 : Model.Books.PageNumber) of @Model.Books.PageCount
        </div>
        <div class="col-md-6">
            @Html.PagedListPager(
                    Model.Books,
                    page => Url.Action("Index",
                                        "AdminBook",
                                        new { page }
                                        ),
                    new PagedListRenderOptions
                    {
                        DisplayLinkToFirstPage = PagedListDisplayMode.Always,
                        DisplayLinkToLastPage = PagedListDisplayMode.Always,
                        DisplayLinkToNextPage = PagedListDisplayMode.IfNeeded,
                        DisplayLinkToPreviousPage = PagedListDisplayMode.IfNeeded,

                        UlElementClasses = new string[] { "pagination", "justify-content-end" },
                        LiElementClasses = new string[] { "page-item" },
                        PageClasses = new string[] { "page-link" },

                        LinkToFirstPageFormat = "<i class='fas fa-fast-backward'></i>",
                        LinkToLastPageFormat = "<i class='fas fa-fast-forward'></i>",
                        LinkToPreviousPageFormat = "<i class='fas fa-backward'></i>",
                        LinkToNextPageFormat = "<i class='fas fa-forward'></i>"

                    }
                )
        </div>
    </div>
</div>